defaults: &default_settings
  ui:
    jobs: #%w{Jobs::Series::UpdateAll Jobs::Image::UpdateAll}
      cloud:
        - Jobs::Cloud::Update
  deploy:
    update:
      - mystro-common
      - mystro-client
      - damsel
      - qujo
      - mystro-chef

development:
  <<: *default_settings

production:
  <<: *default_settings
