defaults: &default_settings
  ui:
    jobs:
      cloud:
        - Jobs::Cloud::Update
  deploy:
    update:
      - mystro-common
      - mystro-client
      - damsel
      - qujo
      - mystro-chef

development:
  <<: *default_settings

production:
  <<: *default_settings
