require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComputesController do
  login_user

  # This should return the minimal set of attributes required to create a valid
  # Compute. As you add validations to Compute, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
        name: "app",
        num: 0,
        flavor: "m1.small"
    }
  end

  describe "GET index" do
    it "assigns all computes as @computes" do
      compute = Compute.create! valid_attributes
      get :index, {}
      assigns(:computes).should eq([compute])
    end
  end

  describe "GET show" do
    it "assigns the requested compute as @compute" do
      compute = Compute.create! valid_attributes
      get :show, {:id => compute.to_param}
      assigns(:compute).should eq(compute)
    end
  end

  describe "GET new" do
    it "assigns a new compute as @compute" do
      get :new, {}
      assigns(:compute).should be_a_new(Compute)
    end
  end

  describe "GET edit" do
    it "assigns the requested compute as @compute" do
      compute = Compute.create! valid_attributes
      get :edit, {:id => compute.to_param}
      assigns(:compute).should eq(compute)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Compute" do
        expect {
          post :create, {:compute => valid_attributes}
        }.to change(Compute, :count).by(1)
      end

      it "assigns a newly created compute as @compute" do
        post :create, {:compute => valid_attributes}
        assigns(:compute).should be_a(Compute)
        assigns(:compute).should be_persisted
      end

      it "redirects to the created compute" do
        post :create, {:compute => valid_attributes}
        response.should redirect_to(Compute.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved compute as @compute" do
        # Trigger the behavior that occurs when invalid params are submitted
        Compute.any_instance.stub(:save).and_return(false)
        post :create, {:compute => {}}
        assigns(:compute).should be_a_new(Compute)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Compute.any_instance.stub(:save).and_return(false)
        post :create, {:compute => {}}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested compute" do
        compute = Compute.create! valid_attributes
        # Assuming there are no other computes in the database, this
        # specifies that the Compute created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Compute.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => compute.to_param, :compute => {'these' => 'params'}}
      end

      it "assigns the requested compute as @compute" do
        compute = Compute.create! valid_attributes
        put :update, {:id => compute.to_param, :compute => valid_attributes}
        assigns(:compute).should eq(compute)
      end

      it "redirects to the compute" do
        compute = Compute.create! valid_attributes
        put :update, {:id => compute.to_param, :compute => valid_attributes}
        response.should redirect_to(compute)
      end
    end

    describe "with invalid params" do
      it "assigns the compute as @compute" do
        compute = Compute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Compute.any_instance.stub(:save).and_return(false)
        put :update, {:id => compute.to_param, :compute => {}}
        assigns(:compute).should eq(compute)
      end

      it "re-renders the 'edit' template" do
        compute = Compute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Compute.any_instance.stub(:save).and_return(false)
        put :update, {:id => compute.to_param, :compute => {}}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested compute" do
      compute = Compute.create! valid_attributes
      expect {
        delete :destroy, {:id => compute.to_param}
      }.to change(Compute, :count).by(-1)
    end

    it "redirects to the computes list" do
      compute = Compute.create! valid_attributes
      delete :destroy, {:id => compute.to_param}
      response.should redirect_to(computes_url)
    end
  end

end
